window.csacompatVersion="3";window.csapacketVersion="1";window.csauseCorsForInitialRequest="1";window.csauseJsonFormatForInitialCorsRequest="1";window.CelebrusDataPrivacy={MAY_CONTAIN_PERSONAL_DATA:1,ANONYMOUS_DATA_ONLY:2};
l.csaexecuteJsonResponse=function(a,d){var c=a,b=window.csawid;d||(c=JSON.parse(a));var f=c.windowVariables,e;for(e in f)0===e.indexOf("csa")&&(window[e]="csauSC"==e||"csauseCors"==e||"csadoCapture"==e||"csalookups"==e||"csauseJsonFormatRequest"==
e?"true"==f[e]:"csaidl"==e||"csasST"==e||"csamST"==e?parseInt(f[e],10):f[e]);if(f=c.queueNavigatorInfo)window.csaqNI=f;if(c.isExcludedFromSample&&csasetShutdown)csasetShutdown();else{(f=c.isMinimalCookieFormat)?(window.csadeleteLegacyCookies&&window.csadeleteLegacyCookies(),csasessionset(c.sessionCookieValue)):(csalegacyset(c.sn,c.lastActivityTs,c.sessionStartTs,c.lbId),csakeyset(c.sessionKey));window.csadoCelebrusInsertInvocation&&
window.csadoCelebrusInsertInvocation(b);if(b=c.persistedCookieValues)f?csapersisted(b.dbID,b.rtId,b.acq,b.sn,b.cookieName,b.cookieExpiry,b.frq,b.acqTS,b.recTS,b.trackDevices):(b.trackDevices?csauvt(b.acq,b.sn,b.cookieExpiry,b.acqTS,b.recTS):csadoDeleteCookie&&csadoDeleteCookie("csauvt"),csadoDeleteCookie&&csadoDeleteCookie("csaDBID"),csaDBIDset(b.dbID+"_"+b.rtId,b.cookieExpiry));if(c.contentResponse&&window.csaRTEHandler){b=
[];try{b=JSON.parse(c.contentResponse)}catch(g){}try{window.csaRTEHandler.handleResponse(b)}catch(g){}}}};
function csasetShutdown(){window.csadeleteSessionCookie&&window.csadeleteSessionCookie();var a=(new Date).valueOf();if(window.csaGD){var k=window.csaGD();document.cookie="csaSF="+a+";path=/"+k}else window.csaSC&&window.csaSC("csaSF="+a)}

window.csaRTEHandler={maxWaitDurationMillis:1E4,maxActionProcessDurationMillisToAllowRequeue:50,targetMissingPollingDurationMillis:250,domContentReadyPollingDurationMillis:100,injectionCount:0,staleCount:0,rejectedCount:0,errorCount:0,nameVal:"RTEHandler",currentActionID:"",currentRuleID:"",currentContentID:"",currentCustomID:"",queue:[],handleResponse:function(a,c){if(!a||!a.length||!c&&-1<document.cookie.indexOf("csaSF=y"))return 0;var b=this.getTimestampMillis(),d,e,f;d=0;for(e=a.length;d<e;d++){f=a[d];try{f.queueTimestampMillis=b;if(f.content&&(f.content=this.doUnescape(f.content),f.parsedContent=this.parseContent(f.content),
!f.parsedContent)){this.rejectedCount++;continue}f.externalContentId&&(f.externalContentId=this.doUnescape(f.externalContentId));f.replacementurl&&(f.replacementurl=this.doUnescape(f.replacementurl));f.idValue&&(f.idValue=this.doUnescape(f.idValue));this.validVariables(f.csaNumber,f.contentKey)?f.csaCallbackTime?this.doCallback(f):this.queueAction(f):this.distributeActionToChildCsas(f)||this.queueAction(f)}catch(g){this.rejectedCount++,this.handleError(g)}}return this.processQueue()}};
;